API_BASE_URL = "https://ghibliapi.herokuapp.com/"
MAX_NETWORK_RETRIES = 10
DELAY_NETWORK_RETRY = 3
CACHED_LIST_ENDPOINTS = 60
CACHED_LIST_MAX_ITEMS = 1024

CACHED_RETRIEVE_ENDPOINTS = 60
CACHED_RETRIEVE_MAX_ITEMS = 1024
